main/urls.py
from django.urls import path, include
from .views import HomeView, login_view, register_user, logout_view

app_name = "main"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),

    # Project URLs
    path("projects/", include(("main.project_urls", "main"), namespace="projects")),

    # Task URLs
    path("tasks/", include(("main.task_urls", "main"), namespace="tasks")),

    # Worker URLs
    path("workers/", include(("main.worker_urls", "main"), namespace="workers")),

    # TaskType URLs
    path("tasktypes/", include(("main.tasktype_urls", "main"), namespace="tasktypes")),

    # Auth
    path("login/", login_view, name="login"),
    path("register/", register_user, name="register"),
    path("logout/", logout_view, name="logout"),
]

portfolio_it_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    #path("accounts/", include("django.contrib.auth.urls")),
    path("", include("main.urls")),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
    IT Projects
    {% endblock %}
  </title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">IT Project Manager</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:project-list' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:task-list' %}">Tasks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:worker-list' %}">Workers</a>
          </li>

          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:my-tasks' %}">🧾 My Tasks</a>
            </li>
            <li class="nav-item">
              <span class="navbar-text text-white mx-2">
                Hello, {{ user.first_name|default:user.username }}
              </span>
            </li>
            <li class="nav-item">
              <form method="post" action="{% url 'main:logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-link nav-link" style="display: inline; padding: -5px">Logout</button>
              </form>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:register' %}">Register</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}
    <!-- сюда будет вставляться контент других страниц -->
    {% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>